### ISSUE TITLE
Generic Pagination

### ISSUE THREAD

**Issue by TheSerumDev** [cadenzauk/siesta#6]
Is there a way to make a pagination with the lib directly (also with sql query)? Or another question: How would you do this?

Sorry for abusing the issues for this question but yeah xd

**Comment by mdrodg** [comment]
Coincidentally, the latest release (0.9.1) has some features specifically designed to support pagination.  These are support for the offset clause and also the ability to specify the order by using string column names.  The latter is required because I imagine you will be passed the ordering from the UI and it will reflect the order the user has chosen to sort the rows.

Given that, here is an example:

```
        Tuple2<Long, Long> firstAndLast = insertSalespeople(database, 8);
        System.out.println("The sales people have IDs from " + firstAndLast.item1()  + " to " + firstAndLast.item2());

        int pageSize = 3;
        List<Tuple2<String, Order>> sort = Stream.of(Tuple.of("SURNAME", Order.ASC), Tuple.of("FIRST_NAME", Order.ASC)).collect(toList());
        int count = database.from(SalespersonRow.class)
            .select(count())
            .where(SalespersonRow::salespersonId).isBetween(firstAndLast.item1()).and(firstAndLast.item2())
            .single();
        int numberOfPages = (count + pageSize - 1) / pageSize;
        for (int pageNo = 0; pageNo < numberOfPages; pageNo++) {
            InOrderByExpectingThen<Long> stmt = database.from(SalespersonRow.class, "s")
                .select(SalespersonRow::salespersonId)
                .where(SalespersonRow::salespersonId).isBetween(firstAndLast.item1()).and(firstAndLast.item2())
                .orderBy("s", sort.get(0).item1(), sort.get(0).item2());
            for (int i = 1; i < sort.size(); i++) {
                stmt = stmt.then("s", sort.get(i).item1(), sort.get(i).item2());
            }
            List<Long> pageOfResults = stmt.offset(pageNo * pageSize).fetchFirst(pageSize).list();
            System.out.println(pageOfResults.stream().map(it -> it.toString()).collect(Collectors.joining(", ", "[", "]")));
        }
```

This produced the following output:

```
The sales people have IDs from 1 to 8
2024-10-25 22:10:29.443 DEBUG [Test worker] | select count(*) as count_1 from SIESTA.SALESPERSON SALESPERSON where SALESPERSON.SALESPERSON_ID between ? and ? | c.c.c.s.ConnectionUtil:73
2024-10-25 22:10:29.448 DEBUG [Test worker] | select s.SALESPERSON_ID as s_SALESPERSON_ID from SIESTA.SALESPERSON s where s.SALESPERSON_ID between ? and ? order by s.SURNAME asc, s.FIRST_NAME asc fetch first 3 rows only | c.c.c.s.ConnectionUtil:73
[5, 1, 4]
2024-10-25 22:10:29.451 DEBUG [Test worker] | select s.SALESPERSON_ID as s_SALESPERSON_ID from SIESTA.SALESPERSON s where s.SALESPERSON_ID between ? and ? order by s.SURNAME asc, s.FIRST_NAME asc offset 3 rows fetch next 3 rows only | c.c.c.s.ConnectionUtil:73
[6, 8, 3]
2024-10-25 22:10:29.453 DEBUG [Test worker] | select s.SALESPERSON_ID as s_SALESPERSON_ID from SIESTA.SALESPERSON s where s.SALESPERSON_ID between ? and ? order by s.SURNAME asc, s.FIRST_NAME asc offset 6 rows fetch next 3 rows only | c.c.c.s.ConnectionUtil:73
[2, 7]
```

**Comment by TheSerumDev** [comment]
So you wouldn't create a generic method/class to support pagination in your project? But thank you for giving me an example. I read that the offset will be slow. Would you still do this with offset?

**Comment by TheSerumDev** [comment]
> So you wouldn't create a generic method/class to support pagination in your project? But thank you for giving me an example. I read that the offset will be slow. Would you still do this with offset?

https://hackernoon.com/dont-offset-your-sql-querys-performance

**Comment by mdrodg** [comment]
That depends on the sort order of your data and whether you have an index that matches that order.  If you have sufficient control so that you can make this true, then no, I would not use offset.  I would perform a query with a where clause to start scanning using the index after the last row of the previous page.  This will give optimum performance.

However, in the general case where you have an arbitrary ordering (perhaps determined by a user) that does not match any index then I would use offset, because really it would make very little difference.  Consider what the DBMS has to do.  It must fetch all the rows that match your criteria, sort them by the order the user want to see, and then return the page using offset and limit.  The expensive part is the fetching and sorting.

The alternative to offset is to again add criteria to your where clause to select rows after the last row on the previous page.  This will have no effect on the first page, negligble effect on the second page, but increasing savings as you get towards the last page, due to the reduced number of rows that need to be sorted.  However it will have no effect on how long it takes to fetch the rows or how long it takes to return them.  IMO the negligible savings for later pages do not merit the added complexity.

I propose adding a page method the select builder which does all the necessary offset, limit and order by operations.  It would look like this:

```
int pageSize = 3;
List<Ordering> ordering = ImmutableList.of(new Ordering("SURNAME", Order.ASC), new Ordering("FIRST_NAME", Order.ASC));
int count = database.from(SalespersonRow.class)
        .select(count())
        .where(SalespersonRow::salespersonId).isBetween(firstAndLast.item1()).and(firstAndLast.item2())
        .single();
int numberOfPages = (count + pageSize - 1) / pageSize;
for (int pageNo = 0; pageNo < numberOfPages; pageNo++) {
    List<Long> pageOfResults = database.from(SalespersonRow.class, "s")
            .select(SalespersonRow::salespersonId)
            .where(SalespersonRow::salespersonId).isBetween(firstAndLast.item1()).and(firstAndLast.item2())
            .page(pageNo, pageSize, ordering)
            .list();
    System.out.println(pageOfResults.stream().map(Object::toString).collect(Collectors.joining(", ", "[", "]")));
}
```
The SQL generated would be the same as the code I presented earlier.

Would you find this helpful?
```

**Comment by TheSerumDev** [comment]
Yes, it would be cool if you added a “page” method like in your example above. And thank you very much, you helped me a lot with the pagination. When will the update come?

**Comment by mdrodg** [comment]
The page method has been added in release 0.9.2 just out.  It differs only from the example above in the fact that I decided it would be more natural to start with page 1 rather than page 0.  See 

https://github.com/cadenzauk/siesta/blob/master/siesta-mariadb/src/test/java/com/cadenzauk/siesta/mariadb/DatabaseIntegrationTestMariaDb.java

for a revised example.

**Comment by TheSerumDev** [comment]
alr. thank you for your help! i'll try it.
